# Generated by Django 5.2.1 on 2025-06-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options_userprofile_dark_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='departments',
        ),
    ]
