# Generated by Django 4.2.7 on 2025-06-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department_ids',
        ),
        migrations.AddField(
            model_name='student',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
