# Generated by Django 5.2.1 on 2025-06-06 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=255)),
                ('student_count', models.IntegerField(default=0)),
                ('teacher_count', models.IntegerField(default=0)),
                ('document_count', models.IntegerField(default=0)),
                ('quiz_count', models.IntegerField(default=0)),
                ('icon', models.CharField(default='school', max_length=50)),
                ('color', models.CharField(default='#4285F4', max_length=20)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
    ]
