# Generated by Django 5.2.1 on 2025-06-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_sno_field'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers who belong to this department', related_name='departments', to='accounts.teacher'),
        ),
    ]
