# Generated by Django 5.2.1 on 2025-06-11 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_sno_field'),
        ('departments', '0002_add_sno_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teachers who belong to this department', related_name='departments', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
