# Generated by Django 4.2.7 on 2025-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_table_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=21, null=True, unique=True),
        ),
    ]
