# Generated by Django 5.2.1 on 2025-06-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_change_primary_key'),
        ('departments', '0005_alter_department_code_alter_department_created_at_and_more'),
    ]

    operations = [
    ]
