# Generated by Django 5.2.1 on 2025-06-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_document_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='share_url',
            field=models.URLField(blank=True, help_text='URL for sharing the quiz', max_length=500, null=True),
        ),
    ]
