# Generated by Django 5.2.1 on 2025-06-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_share_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the quiz', null=True),
        ),
    ]
