# Generated by Django 5.2.1 on 2025-06-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentvector'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='quiz.quiz'),
        ),
    ]
