# Generated by Django 5.2.1 on 2025-06-20 04:59

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.document_file_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('supabase', 'Supabase Storage'), ('s3', 'AWS S3'), ('vector_db', 'Vector Database')], default='local', max_length=20),
        ),
    ]
