# Generated by Django 4.2.7 on 2025-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='departments',
        ),
        migrations.AddField(
            model_name='teacher',
            name='department_ids',
            field=models.JSONField(default=list),
        ),
    ]
