# Generated by Django 4.2.7 on 2025-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_departments_teacher_department_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
